name: contact
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  sqflite:
  path:
  url_launcher: ^5.4.2
  local_auth: ^0.6.1+3
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0
flutter:


  uses-material-design: true

  assets:
    - assets/images/profile-picture.png
  #   - images/a_dot_ham.jpeg

  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Black.ttf
          - asset: assets/fonts/Poppins-Bold.ttf
          - asset: assets/fonts/Poppins-ExtraBold.ttf
          - asset: assets/fonts/Poppins-ExtraLight.ttf
          - asset: assets/fonts/Poppins-Light.ttf
          - asset: assets/fonts/Poppins-Medium.ttf
          - asset: assets/fonts/Poppins-Regular.ttf
          - asset: assets/fonts/Poppins-SemiBold.ttf
          - asset: assets/fonts/Poppins-Thin.ttf
